# -*- coding: utf-8 -*-
"""simple_CohereChatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9XNm-BItrkAA8Q7SBsHd1222QP3g5O2
"""

!pip install cohere
!pip install gradio

import cohere
import gradio as gr

api_key = "API_KEY"
co = cohere.Client(api_key)

# Chat history to remember previous messages
chat_history = []

def cohere_chat(message):
    global chat_history

    # Build prompt from history
    prompt = ""
    for turn in chat_history[-5:]:  # Limit context
        prompt += f"User: {turn['user']}\nBot: {turn['bot']}\n"
    prompt += f"User: {message}\nBot:"



    try:
        response = co.generate(
            model="command",
            prompt=prompt,
            max_tokens=50,
            temperature=0.5
        )
        reply = response.generations[0].text.strip()

        # Fallback if response is unclear
        if not reply or "i don't know" in reply.lower() or "not sure" in reply.lower():
            reply = "🤔 Sorry, I couldn't understand that. Can you try rephrasing?"

        # Update history
        chat_history.append({"user": message, "bot": reply})
        return reply

    except Exception as e:
        return f"⚠️ Error: {str(e)}"


# Gradio UI
gr.Interface(
    fn=cohere_chat,
    inputs="text",
    outputs="text",
    title="🤖 Ask Me Anything",
    description="A simple chatbot powered by Cohere API"
).launch()